# Generated by Django 4.0.5 on 2022-06-22 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título página')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha modificación')),
            ],
        ),
        migrations.CreateModel(
            name='PostPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre proyecto')),
                ('text', models.TextField(max_length=500, verbose_name='Descripción Proyecto')),
                ('image', models.ImageField(default='null', upload_to='projects', verbose_name='Foto proyecto')),
                ('languajes', models.CharField(max_length=350, verbose_name='Lenguajes ocupados')),
                ('framework', models.CharField(default='null', max_length=200, verbose_name='Framework')),
                ('project_date', models.DateTimeField(verbose_name='Fecha realización proyecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('uptaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
        ),
    ]
