# Generated by Django 4.0.5 on 2022-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_enviarcontacto_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviarcontacto',
            name='message',
            field=models.TextField(default='Write your message here :)'),
        ),
    ]
