# Generated by Django 4.0.5 on 2022-06-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_enviarcontacto_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviarcontacto',
            name='email',
            field=models.EmailField(default='mail@yourmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='enviarcontacto',
            name='title',
            field=models.CharField(default='yourname', max_length=100),
        ),
    ]
