# Generated by Django 4.0.5 on 2022-06-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_enviarcontacto_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviarcontacto',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enviarcontacto',
            name='phone',
            field=models.IntegerField(default=34),
        ),
        migrations.AlterField(
            model_name='enviarcontacto',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
