# Generated by Django 4.0.5 on 2022-07-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_enviarcontacto_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postportfolio',
            name='image',
            field=models.ImageField(default='null', upload_to='img_portfolio', verbose_name='Foto proyecto'),
        ),
    ]
