# Generated by Django 4.0.5 on 2022-07-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_postportfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postportfolio',
            name='project_date',
            field=models.DateField(verbose_name='Fecha realización proyecto'),
        ),
    ]
