# Generated by Django 4.0.5 on 2022-07-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_postportfolio_project_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título Artículo')),
                ('description', models.TextField(verbose_name='Contenido Blog')),
                ('image', models.ImageField(default='null', upload_to='img_blog', verbose_name='Imagen Blog')),
                ('created_at', models.DateField(verbose_name='Fecha creación')),
                ('updated_at', models.DateField(verbose_name='Fecha actualización')),
            ],
        ),
    ]
